### ISSUE TITLE
Bug: Attempting to play video not in current set of playlists

### ISSUE THREAD

**Issue by hebron-george** [happy-software/shuffle_youtube_playlist#53]
## Description

Attempting to play a video that's not in the current set of combined playlists will cause the app to crash.

I haven't dug into it deeply, but based on the error message in console, I suspect it's trying to do a lookup in the list of videos based on the `video_id`.

## Error message
![Screen Shot 2021-08-01 at 9 10 31 PM](https://user-images.githubusercontent.com/1514459/127791909-3398eb97-87ad-4fec-9f73-e43605908b07.png)

## Steps to Replicate
1. Load the app and play the first video that pops up
2. Unselect all playlists and choose a playlist you know doesn't have that first video in it
3. Combine playlists
4. Once a new song loads up, click on that first song from the played video history list -- *crash*

**Comment by ras1** [comment]
Since we don’t have history anymore this isn’t possible to replicate. Do we want history back?

**Comment by ras1** [comment]
@hebron-george

**Comment by hebron-george** [comment]
I'd like a play history somewhere yeah. But not at the expense of losing media controls. This specific issue is no longer needed but we should replace it with an issue to research a way to track playlist history.
